paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos OK desde la DB
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lista de productos"
                  productos:
                    type: array
                    items:
                      $ref: '#components/schemas/Products'
        # "500":
        #   description: Error interno del servidor
    post:
      summary: Graba un nuevo producto
      tags:
        - Products
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ejemplo de un producto:"
                  productos:
                    type: array
                    items:
                      $ref: '#components/schemas/Products'
        "500":
          description: Error interno del servidor